apiVersion: v1
kind: Service
metadata:
  name: express-graphql-service
spec:
  selector:
    app: express-graphql-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: express-graphql-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer